# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trial',
            options={'ordering': ['num']},
        ),
        migrations.AddField(
            model_name='trial',
            name='num',
            field=models.CharField(default=2, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
